language: R
sudo: required
warnings_are_errors: true

env: 
  global:
    - CRAN: https://cran.rstudio.com

before_script:
  - git clone git://github.com/jedisct1/libsodium.git
  - ( cd libsodium; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )

before_install:
  - sudo apt-get install -qq libzmq3-dev
  
r_packages:
  - assertthat
  - sodium
  - pbdZMQ
