language: R
sudo: required
warnings_are_errors: true

env: 
  global:
    - CRAN: https://cran.rstudio.com
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - _R_CHECK_TIMINGS_="0"

before_install:
  - sudo apt-get install -qq libzmq3-dev
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - ./autogen.sh
  - ./configure --disable-dependency-tracking --enable-minimal
  - make
  - sudo make install
  - sudo /sbin/ldconfig
  - cd ..
  - rm -rf libsodium
  
r_packages:
  - assertthat
  - pbdZMQ
  - sodium
