language: R
sudo: required
warnings_are_errors: true

env: 
  global:
    - CRAN: https://cran.rstudio.com

before_install:
  - sudo apt-get install -qq libzmq3-dev libsodium-dev

r_packages:
  - assertthat
  - sodium
  - pbdZMQ
