language: R
sudo: required
warnings_are_errors: true

env: 
  global:
    - CRAN: https://cran.rstudio.com

before_script:
  - sudo apt-get install -qq libzmq3-dev

r_packages:
  - assertthat

r_github_packages:
  - snoweye/pbdZMQ
